name: wiki
on:
  push:
    paths:
      - 'docs/*'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish
        shell: bash
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git clone https://vika:${TOKEN}@github.com/${{env.GITHUB_ACTION_REPOSITORY}}.wiki.git wiki
          # ensure old files are cleaned up
          rm -rf wiki/*
          cp -r docs/* wiki
          cd wiki
          git config --local user.email "test@test.com"
          git config --local user.name "github_user"
          git add .
          git commit -m "update wiki pages"
          git push https://github_user:${token}@github.com/${{env.GITHUB_ACTION_REPOSITORY}}.wiki.git
          cd ..
          rm -rf wiki

