name: wiki
on:
  push:
    paths:
      - 'docs/*'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: copy docs folder
        run: |
          rm -rf wiki/*
          cp -r repo/docs/* wiki/
          pushd wiki >/dev/null 2>&1
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "update wiki"
      - name: push wiki changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
