name: wiki
on:
  push:
    paths:
      - 'docs/*'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: copy docs folder
        run: |
          rm -rfv wiki/*
          cp -rv repo/docs/* wiki/
      - name: actually push changes
        run: |
          pushd wiki >/dev/null 2>&1
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "update wiki"
          git push
